name: Post Release

on:
  push:
    branches:
      # all branches
      - '*'

jobs:
  release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        echo 'y' | sudo apt-get install p7zip-full

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Build
      run: |
        npm install
        npm run build
        ./node_modules/.bin/oclif pack tarballs --parallel --no-xz

    - name: Rename files
      run: |
        chmod +x ./src/bash/workflows/rename-dist.sh
        ./src/bash/workflows/rename-dist.sh

    - name: save asset name
      id: save_asset_name
      run: |
        ASSET_PATH=$(find ./dist/ -name "*linux-x64*")
        echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
        ASSET_NAME=$(basename $ASSET_PATH)
        echo "ASSET_NAME=$ASSET_NAME" >> $GITHUB_ENV
        TAG_NAME="$ASSET_NAME-$RANDOM"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.ASSET_NAME }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{  env.ASSET_PATH }}
        asset_name: ${{  env.ASSET_NAME }}
        asset_content_type: application/gzip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
